version: '3.7'

networks:
  webnet:
  db_network:

services:
  role-based-backend:
    container_name: role-based-backend
    restart: on-failure
    volumes:
      - .:/app
    build:
      context: .
      dockerfile: Dockerfile.local
    env_file: .env
    networks:
      - webnet
      - db_network
    depends_on:
      role-based-backend-db:
        condition: service_healthy
    ports:
      - "8000:8000"
    entrypoint: ["/app/setup_local_enviroment"]

  role-based-backend-db:
      container_name: role-based-backend-db
      image: postgres:13-alpine
      restart: on-failure
      healthcheck:
        test: ["CMD-SHELL", "pg_isready"]
        interval: 10s
        timeout: 5s
        retries: 5
      volumes:
        - ./setup/docker/postgres:/var/lib/postgresql/data
      env_file: .env
      ports:
        - '5432:5432'
      networks:
        - db_network

  role-based-backend-unit-tests:
    container_name: role-based-backend-unit-tests
    restart: on-failure
    volumes:
      - .:/app
    build:
      context: .
      dockerfile: Dockerfile.local
    env_file: .env
    networks:
      - webnet
      - db_network
    ports:
      - "8001:8000"
    entrypoint: ["/app/setup_local_enviroment"]
