FROM python:3.11.2-buster

RUN mkdir -p /home/app
ENV HOME=/home/app

ENV APP_HOME=/app
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

RUN apt-get update -y && apt-get upgrade -y

ADD pyproject.toml poetry.lock /app/

RUN pip install poetry && poetry install --no-root
