#!/usr/bin/env bash

echo "Running migrations"
poetry run alembic upgrade head
echo "Migrations done"

echo "Running project"
exec poetry run uvicorn --host 0.0.0.0 --port 8000 role_based_app.main:app --reload
